#platform_malloc="-DJEMALLOC_ROOT=$HOME/install/jemalloc-3.5.1"
#platform_malloc="-DGPERFTOOLS_ROOT=/usr/local/gperftools/2.5"
#platform_malloc="-DAPEX_WITH_JEMALLOC=TRUE"
platform_bfd="-DAPEX_WITH_BFD=FALSE"
platform_ah="-DAPEX_BUILD_ACTIVEHARMONY=TRUE"
platform_otf="-DAPEX_BUILD_OTF2=TRUE"
platform_ompt="-DAPEX_BUILD_OMPT=TRUE -DAPEX_WITH_PLUGINS=TRUE"
platform_mpi="-DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DAPEX_WITH_MPI=TRUE"
platform_papi="-DAPEX_WITH_PAPI=TRUE -DPAPI_ROOT=$HOME/install/papi-5.3.0"
platform_tau="-DAPEX_WITH_TAU=TRUE -DTAU_ROOT=$HOME/src/tau2 -DTAU_ARCH=apple -DTAU_OPTIONS=-pthread"

parallel_build="-j 8"
