#platform_malloc="-DJEMALLOC_ROOT=$HOME/install/jemalloc-3.5.1"
#platform_malloc="-DGPERFTOOLS_ROOT=/usr/local/gperftools/2.5"
#platform_malloc="-DUSE_JEMALLOC=TRUE"
platform_bfd="-DUSE_BFD=FALSE"
platform_ah="-DBUILD_ACTIVEHARMONY=TRUE"
platform_otf="-DBUILD_OTF2=TRUE"
platform_ompt="-DBUILD_OMPT=TRUE -DUSE_PLUGINS=TRUE"
platform_mpi="-DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DUSE_MPI=TRUE"
platform_papi="-DUSE_PAPI=TRUE -DPAPI_ROOT=$HOME/install/papi-5.3.0"
platform_tau="-DUSE_TAU=TRUE -DTAU_ROOT=$HOME/src/tau2 -DTAU_ARCH=apple -DTAU_OPTIONS=-pthread"

parallel_build="-j 8"
