#!/bin/bash

LANG="C"
export LANG

if [ `uname -s ` = Darwin ]; then
  apple=1
  SHLIBX=.dylib
else
  apple=0
  SHLIBX=.so
fi

# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
#echo $SCRIPTPATH
BASEDIR="$(dirname $SCRIPTPATH)"

usage() {
    message="
Usage:
$(basename "$0") <APEX options> executable <executable options>

where APEX options are zero or more of:
    --apex:help            show this usage message
    --apex:debug           run with APEX in debugger
    --apex:verbose         enable verbose list of APEX environment variables
    --apex:screen          enable screen text output (on by default)
    --apex:quiet           disable screen text output
    --apex:csv             enable csv text output
    --apex:tau             enable tau profile output
    --apex:taskgraph       enable taskgraph output
                           (graphviz required for post-processing)
    --apex:tasktree        enable tasktree output
                           (graphviz required for post-processing)
    --apex:otf2            enable OTF2 trace output
    --apex:otf2path        specify location of OTF2 archive
                           (default: ./OTF2_archive)
    --apex:otf2name        specify name of OTF2 file (default: APEX)
    --apex:gtrace          enable Google Trace Events output
    --apex:scatter         enable scatterplot output
                           (python required for post-processing)
    --apex:openacc         enable OpenACC support
    --apex:kokkos          enable Kokkos support
    --apex:raja            enable RAJA support
    --apex:pthread         enable pthread wrapper support
    --apex:memory          enable memory wrapper support
    --apex:untied          enable tasks to migrate cores/OS threads
                           during execution (not compatible with trace output)
    --apex:cuda            enable CUDA/CUPTI measurement (default: off)
    --apex:cuda_counters   enable CUDA/CUPTI counter support (default: off)
    --apex:cuda_driver     enable CUDA driver API callbacks (default: off)
    --apex:cuda_details    enable per-kernel statistics where available (default: off)
    --apex:hip             enable HIP/ROCTracer measurement (default: off)
    --apex:hip_counters    enable HIP/ROCTracer counter support (default: off)
    --apex:hip_driver      enable HIP/ROCTracer KSA driver API callbacks (default: off)
    --apex:hip_details     enable per-kernel statistics where available (default: off)
    --apex:cpuinfo         enable sampling of /proc/cpuinfo (Linux only)
    --apex:meminfo         enable sampling of /proc/meminfo (Linux only)
    --apex:net             enable sampling of /proc/net/dev (Linux only)
    --apex:status          enable sampling of /proc/self/status (Linux only)
    --apex:io              enable sampling of /proc/self/io (Linux only)
    --apex:period          specify frequency of OS/HW sampling
    --apex:ompt            enable OpenMP profiling (requires runtime support)
    --apex:ompt_simple     only enable OpenMP Tools required events
    --apex:ompt_details    enable all OpenMP Tools events
    "
    echo "${message}"
    exit 1
}

openacc=no
kokkos=no
raja=no
otf2=no
gtrace=no
scatter=no
taskgraph=no
tasktree=no
screen=yes
csv=no
tau=no
debug=no
cuda=no
cuda_counters=no
cuda_driver=no
cuda_details=no
hip=no
hip_counters=no
hip_driver=no
hip_details=no
untied=no
cpuinfo=no
meminfo=no
ompt=no
net=no
stat=no
period=1000000
io=no
pthread=no
memory=no
policy=yes
debugger=""
prog=""

if [ $# -eq 0 ] ; then
    usage
fi

PARAMS=""
while (( "$#" )); do
  case "$1" in
    --apex:openacc)
      openacc=yes
      shift
      ;;
    --apex:kokkos)
      kokkos=yes
      shift
      ;;
    --apex:raja)
      raja=yes
      shift
      ;;
    --apex:debug)
      debug=yes
      shift
      ;;
    --apex:pthread)
      pthread=yes
      export APEX_TIME_TOP_LEVEL_OS_THREADS=1
      shift
      ;;
    --apex:memory)
      memory=yes
      export APEX_TRACK_MEMORY=1
      export APEX_SOURCE_LOCATION=1
      shift
      ;;
    --apex:otf2)
      otf2=yes
      export APEX_OTF2=1
      shift
      ;;
    --apex:verbose)
      export APEX_VERBOSE=1
      shift
      ;;
    --apex:gtrace)
      gtrace=yes
      export APEX_TRACE_EVENT=1
      shift
      ;;
    --apex:scatter)
      scatter=yes
      export APEX_TASK_SCATTERPLOT=1
      shift
      ;;
    --apex:taskgraph)
      taskgraph=yes
      export APEX_TASKGRAPH_OUTPUT=1
      shift
      ;;
    --apex:tasktree)
      tasktree=yes
      export APEX_TASKTREE_OUTPUT=1
      shift
      ;;
    --apex:screen)
      screen=yes
      shift
      ;;
    --apex:quiet)
      screen=no
      shift
      ;;
    --apex:csv)
      csv=yes
      export APEX_CSV_OUTPUT=1
      shift
      ;;
    --apex:tau)
      tau=yes
      export APEX_PROFILE_OUTPUT=1
      shift
      ;;
    --apex:cuda)
      export APEX_ENABLE_CUDA=1
      shift
      ;;
    --apex:cuda_counters)
      cuda_counters=yes
      export APEX_ENABLE_CUDA=1
      export APEX_CUDA_COUNTERS=1
      shift
      ;;
    --apex:cuda_driver)
      cuda_driver=yes
      export APEX_ENABLE_CUDA=1
      export APEX_CUDA_DRIVER_API=1
      shift
      ;;
    --apex:cuda_details)
      cuda_details=yes
      export APEX_ENABLE_CUDA=1
      export APEX_CUDA_KERNEL_DETAILS=1
      shift
      ;;
    --apex:hip)
      export APEX_ENABLE_HIP=1
      shift
      ;;
    --apex:hip_counters)
      hip_counters=yes
      export APEX_ENABLE_HIP=1
      export APEX_HIP_COUNTERS=1
      shift
      ;;
    --apex:hip_driver)
      hip_driver=yes
      export APEX_ENABLE_HIP=1
      export APEX_HIP_KFD_API=1
      shift
      ;;
    --apex:hip_details)
      hip_details=yes
      export APEX_ENABLE_HIP=1
      export APEX_HIP_KERNEL_DETAILS=1
      shift
      ;;
    --apex:cpuinfo)
      cpuinfo=yes
      export APEX_PROC_CPUINFO=1
      shift
      ;;
    --apex:meminfo)
      meminfo=yes
      export APEX_PROC_MEMINFO=1
      shift
      ;;
    --apex:net)
      net=yes
      export APEX_PROC_NET_DEV=1
      shift
      ;;
    --apex:status)
      stat=yes
      export APEX_PROC_SELF_STATUS=1
      shift
      ;;
    --apex:io)
      io=yes
      export APEX_PROC_SELF_IO=1
      shift
      ;;
    --apex:untied)
      untied=yes
      export APEX_UNTIED_TIMERS=1
      shift
      ;;
    --apex:ompt)
      ompt=yes
      shift
      ;;
    --apex:ompt_simple)
      export APEX_OMPT_REQUIRED_EVENTS_ONLY=1
      shift
      ;;
    --apex:ompt_details)
      export APEX_OMPT_HIGH_OVERHEAD_EVENTS=1
      shift
      ;;
    --apex:otf2path)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        export APEX_OTF2_ARCHIVE_PATH=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        usage
      fi
      ;;
    --apex:otf2name)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        export APEX_OTF2_ARCHIVE_NAME=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        usage
      fi
      ;;
    --apex:period)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        export APEX_PROC_PERIOD=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        usage
      fi
      ;;
    --apex:*) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      usage
      ;;
    *) # preserve positional arguments
      if [ "$prog" = "" ] ; then
        prog=$1
      fi
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "${PARAMS}"

export APEX_POLICY=1
export HARMONY_HOME="@ACTIVEHARMONY_ROOT@"

echo_screen() {
    if [ ${screen} = yes ] ; then
        echo $1
    fi
}

if [ "x${APEX_OUTPUT_FILE_PATH}" = "x" ] ; then
    output_path="."
else
    output_path=${APEX_OUTPUT_FILE_PATH}
fi

echo_screen "Program to run : ${PARAMS}"

if [ "x${LD_LIBRARY_PATH}" = "x" ] ; then
  APEX_LD_LIBRARY_PATH=${BASEDIR}/lib
else
  APEX_LD_LIBRARY_PATH=${BASEDIR}/lib:${LD_LIBRARY_PATH}
fi
if [ $pthread = yes ]; then
    PTHREAD_LIB=${BASEDIR}/lib/libapex_pthread_wrapper${SHLIBX}:
fi
if [ $ompt = yes ]; then
    OMPT_LIB=@OMPT_LIBRARY@:
fi
if [ $memory = yes ]; then
    MEMORY_LIB=${BASEDIR}/lib/libapex_memory_wrapper${SHLIBX}:
    APEX_LD_AUDIT=${BASEDIR}/lib/libapex_dl_auditor${SHLIBX}
fi
if [ ${apple} = 1 ]; then
    APEX_LD_PRELOAD=${PTHREAD_LIB}${MEMORY_LIB}${BASEDIR}/lib/libapex${SHLIBX}:${OMPT_LIB}
else
    APEX_LD_PRELOAD=${PTHREAD_LIB}${MEMORY_LIB}${BASEDIR}/lib/libapex${SHLIBX}:${OMPT_LIB}:${LD_PRELOAD}
fi

# remove spaces and double colons
APEX_LD_PRELOAD=`echo ${APEX_LD_PRELOAD} | sed -e "s/ /:/g" -e "s/::/:/g" -e "s/:$//"`
export CPUPROFILE=two_vars.prof

if [ ${apple} = 1 ]; then
  APEX_LDD='otool -L'
else
  APEX_LDD=ldd
fi

if [ ! -x "${prog}" ] ; then
    prog=`which ${prog} 2>/dev/null`
fi

if [ ! -x "${prog}" ] ; then
    echo "apex_exec: $1: command not found"
    exit
fi

if [ $apple = 1 ]; then
    export DYLD_LIBRARY_PATH=${APEX_LD_LIBRARY_PATH}
    export DYLD_INSERT_LIBRARIES=${APEX_LD_PRELOAD}
    export DYLD_FORCE_FLAT_NAMESPACE=1
    if [ $debug = yes ] ; then
        echo "_regexp-env DYLD_LIBRARY_PATH=${APEX_LD_LIBRARY_PATH}" >> ./.gdbcmds
        echo "_regexp-env DYLD_INSERT_LIBRARIES=${APEX_LD_PRELOAD}" >> ./.gdbcmds
        echo "_regexp-env DYLD_FORCE_FLAT_NAMESPACE=1" >> ./.gdbcmds
        debugger="lldb -s ./.gdbcmds --"
        if [ $# -gt 1 ] ; then
            echo "settings set target.run-args ${*:2}" >> .gdb_commands
        fi
    fi
else
    export LD_LIBRARY_PATH=${APEX_LD_LIBRARY_PATH}
    export LD_PRELOAD=${APEX_LD_PRELOAD}
    # Not sure if the DL auditor is necessary
    #export LD_AUDIT=${APEX_LD_AUDIT}
    if [ $debug = yes ] ; then
        echo "set env LD_LIBRARY_PATH=${APEX_LD_LIBRARY_PATH}" >> ./.gdbcmds
        echo "set env LD_PRELOAD=${APEX_LD_PRELOAD}" >> ./.gdbcmds
        #echo "set env LD_AUDIT=${APEX_LD_AUDIT}" >> ./.gdbcmds
        debugger="gdb -x ./.gdbcmds --args"
    fi
fi

if [ ${screen} = yes ] ; then
    export APEX_SCREEN_OUTPUT=1
else
    export APEX_SCREEN_OUTPUT=0
fi

if [ ${kokkos} = yes ] ; then
    export KOKKOS_PROFILE_LIBRARY=${BASEDIR}/lib/libapex${SHLIBX}
fi
if [ ${raja} = yes ] ; then
    export RAJA_PLUGINS=${BASEDIR}/lib/libapex${SHLIBX}
fi
if [ ${openacc} = yes ] ; then
    export ACC_PROFLIB=${BASEDIR}/lib/libapex${SHLIBX}
fi

${debugger} ${PARAMS}
retval=$?
unset LD_PRELOAD
rm -f ./.gdbcmds

if [ ${retval} != 0 ] ; then
    exit ${retval}
fi

cd ${output_path}

if [ ${scatter} = yes ] ; then
    ${SCRIPTPATH}/task_scatterplot.py
    ${SCRIPTPATH}/counter_scatterplot.py
fi

if [ ${taskgraph} = yes ] ; then
    echo_screen "Generating taskgraph with GraphViz..."
    dot -Tpdf -O taskgraph.0.dot
fi

if [ ${tasktree} = yes ] ; then
    echo_screen "Generating tasktree with GraphViz..."
    dot -Tpdf -O tasktree.0.dot
    echo_screen "Human readable tree in tasktree.*.txt:"
    if [ ${screen} = yes ] ; then
        head tasktree.0.txt
    fi
    echo_screen "..."
fi

cd -
